//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSQForecast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumberMapping
    {
        public long TermNum { get; set; }
        public Nullable<bool> RedNum1 { get; set; }
        public Nullable<bool> RedNum2 { get; set; }
        public Nullable<bool> RedNum3 { get; set; }
        public Nullable<bool> RedNum4 { get; set; }
        public Nullable<bool> RedNum5 { get; set; }
        public Nullable<bool> RedNum6 { get; set; }
        public Nullable<bool> RedNum7 { get; set; }
        public Nullable<bool> RedNum8 { get; set; }
        public Nullable<bool> RedNum9 { get; set; }
        public Nullable<bool> RedNum10 { get; set; }
        public Nullable<bool> RedNum11 { get; set; }
        public Nullable<bool> RedNum12 { get; set; }
        public Nullable<bool> RedNum13 { get; set; }
        public Nullable<bool> RedNum14 { get; set; }
        public Nullable<bool> RedNum15 { get; set; }
        public Nullable<bool> RedNum16 { get; set; }
        public Nullable<bool> RedNum17 { get; set; }
        public Nullable<bool> RedNum18 { get; set; }
        public Nullable<bool> RedNum19 { get; set; }
        public Nullable<bool> RedNum20 { get; set; }
        public Nullable<bool> RedNum21 { get; set; }
        public Nullable<bool> RedNum22 { get; set; }
        public Nullable<bool> RedNum23 { get; set; }
        public Nullable<bool> RedNum24 { get; set; }
        public Nullable<bool> RedNum25 { get; set; }
        public Nullable<bool> RedNum26 { get; set; }
        public Nullable<bool> RedNum27 { get; set; }
        public Nullable<bool> RedNum28 { get; set; }
        public Nullable<bool> RedNum29 { get; set; }
        public Nullable<bool> RedNum30 { get; set; }
        public Nullable<bool> RedNum31 { get; set; }
        public Nullable<bool> RedNum32 { get; set; }
        public Nullable<bool> BlueNum1 { get; set; }
        public Nullable<bool> BlueNum2 { get; set; }
        public Nullable<bool> BlueNum3 { get; set; }
        public Nullable<bool> BlueNum4 { get; set; }
        public Nullable<bool> BlueNum5 { get; set; }
        public Nullable<bool> BlueNum6 { get; set; }
        public Nullable<bool> BlueNum7 { get; set; }
        public Nullable<bool> BlueNum8 { get; set; }
        public Nullable<bool> BlueNum9 { get; set; }
        public Nullable<bool> BlueNum10 { get; set; }
        public Nullable<bool> BlueNum11 { get; set; }
        public Nullable<bool> BlueNum12 { get; set; }
        public Nullable<bool> BlueNum13 { get; set; }
        public Nullable<bool> BlueNum14 { get; set; }
        public Nullable<bool> BlueNum15 { get; set; }
        public Nullable<bool> BlueNum16 { get; set; }
    }
}
