//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSQForecast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalTermInfo
    {
        public long TermNum { get; set; }
        public System.DateTime TermDate { get; set; }
        public int RedNum1 { get; set; }
        public int RedNum2 { get; set; }
        public int RedNum3 { get; set; }
        public int RedNum4 { get; set; }
        public int RedNum5 { get; set; }
        public int RedNum6 { get; set; }
        public int BlueNum { get; set; }
        public decimal TotalPaid { get; set; }
        public decimal PrizePool { get; set; }
        public int FirstPrizeNum { get; set; }
        public decimal AmountPerFirstPrize { get; set; }
        public int SecondPrizeNum { get; set; }
        public decimal AmountPerSecondPrize { get; set; }
        public int ThirdPrizeNum { get; set; }
        public decimal AmountPerThirdPrize { get; set; }
        public int FourthPrizeNun { get; set; }
        public decimal AmountPerFourthPrize { get; set; }
        public int FifthPrizeNum { get; set; }
        public decimal AmountPerFifthPrize { get; set; }
        public int SixthPrizeNum { get; set; }
        public decimal AmountPerSixthPrize { get; set; }
    }
}
