//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSQForecast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalTermInfos
    {
        public long TermNum { get; set; }
        public System.DateTime TermDate { get; set; }
        public long RedNum1 { get; set; }
        public long RedNum2 { get; set; }
        public long RedNum3 { get; set; }
        public long RedNum4 { get; set; }
        public long RedNum5 { get; set; }
        public long RedNum6 { get; set; }
        public long BlueNum { get; set; }
        public long TotalPaid { get; set; }
        public long PrizePool { get; set; }
        public long FirstPrizeNum { get; set; }
        public long AmountPerFirstPrize { get; set; }
        public long SecondPrizeNum { get; set; }
        public long AmountPerSecondPrize { get; set; }
        public long ThirdPrizeNum { get; set; }
        public long AmountPerThirdPrize { get; set; }
        public long FourthPrizeNun { get; set; }
        public long AmountPerFourthPrize { get; set; }
        public long FifthPrizeNum { get; set; }
        public long AmountPerFifthPrize { get; set; }
        public long SixthPrizeNum { get; set; }
        public long AmountPerSixthPrize { get; set; }
    }
}
